### ISSUE TITLE
Al anular la transaccion en la pagina de Transbank me manda a la pagina de exito con webpay plus normal

### ISSUE THREAD

**Issue by hherraz** [freshworkstudio/transbank-web-services#10]

**Comment by gdespirito** [comment]
Hola!. Siempre lleva a la url que marcas como final. Tanto si se aprueba o
se rechaza. Eres tu en el código el que debe definir si "finish.php"
muestra la página de éxito o rechazo.



GONZALO DE-SPIRITO ZÚÑIGA | Web Development
*FRESHWORK STUDIO CHILE*


Fijo: 02 - 2979 0059| Móvil: 881 53 776 |  gonzalo@freshworkstudio.com
<gonzalo@freshworkstudio.com>

Cuida el medio ambiente. No imprimas este e-mail a menos que sea necesario.

2018-03-27 18:16 GMT-03:00 Heber Herraz <notifications@github.com>:

**Comment by hherraz** [comment]
Gracias Gonzalo.... perdona las molestias... me di cuenta despues de preguntarte, que funcionaba de esta manera.

Gran contribución la tuya y si tienes un patreon favor házmelo llegar me encantaría poder donar por tu contribución. 
PD: una ultima consulta sabes cual es el responseCode de la anulacion???

**Comment by ErSoul** [comment]
Hola, en la documentación de esta librería dice que en el método nullify() hay que mandar un código de autorización. ¿De dónde saco este código de autorización, si según la API de Transbank dice que dicho código es devuelto por el método getTransactionResult()?

PD: tuve que cambiar el acceso de WebpayCaptureNullifyWebService::clasmap de *private* a *protected* ya que *laravel* me lo pedía así.
