### ISSUE TITLE
Usar con captura diferida

### ISSUE THREAD

**Issue by techguydev** [freshworkstudio/transbank-web-services#12]
Buenos dias.

Muchas gracias por compartir este repositorio.

Me interesa usar el modo de captura diferida que ofrece transbank, he conversado con el soporte tecnico y me explican que desde el punto de vista del cliente ( nosotros )  el procedimiento es muy similar a una transaccion de webpay normal, con la diferencia que en sus sistemas el monto quedara autorizado  pero no capturado, cuando el metodo Transactionresult nos de respuesta, la misma tendrá el siguiente esquema:

`object(transactionResultOutput)#7 (8) {["accountingDate"]=> string(4) "0429" ["buyOrder"]=> string(13) "5723aff725e98" ["cardDetail"]=> object(cardDetail)#13 (2) { ["cardNumber"]=> string(4) "6623" ["cardExpirationDate"]=> NULL }["detailOutput"]=> object(wsTransactionDetailOutput)#9 (7) {["authorizationCode"]=> string(4) "1213" ["paymentTypeCode"]=> string(2) "VN" ["responseCode"]=> int(0) ["sharesNumber"]=> int(0) ["amount"]=> string(4) "9990" ["commerceCode"]=> string(12) "597020000300" ["buyOrder"]=> string(13) "5723aff725e98" }["sessionId"]=> string(5) "14246" ["transactionDate"]=> string(29) "2016-04-29T14:57:25.472-04:00" ["urlRedirection"]=> string(56) "https://tbk.orangepeople.cl//filtroUnificado/voucher.cgi" ["VCI"]=> string(3) "TSY"}`

El campo "authorizationCode" lo usaremos luego para poder capturar el monto igual o menor al autorizado previamente.

He visto en el repositorio que el archivo WebpayNormalAnulacion.php tiene  una clase llamada "WebpayNormalAnulacion" la cual tiene la funcion Capture ya incluida.

Tienen algun ejemplo  que puedan compartir para implementar la captura diferida con este repositorio?

Muchas gracias.

**Comment by gdespirito** [comment]
Hola! Ví qeu hiciste un fork y al parecer pudiste implementar la captura diferida. ¿Te funcionó finalmente? Si es así podrías hacer un pull request y así integramos esa funcionalidad al paquete. 

Quedo atento!

**Comment by techguydev** [comment]
Hola, si  efectivamente he logrado hacer funcionar el paquete con  el modo de captura diferida, voy a hacerle unas modificaciones y agregarle la documentación para hacer el pull request.

**Comment by gdespirito** [comment]
Gracias!
