### ISSUE TITLE
Identificar resultado exitoso PatPass

### ISSUE THREAD

**Issue by isaiasmac** [freshworkstudio/transbank-web-services#2]
$response = $patpass->getTransactionResult();
//If everything goes well (check stock, check amount, etc) you can call acknowledgeTransaction to accept the payment. Otherwise, the transaction is reverted in 30 seconds.
//Si todo está bien, peudes llamar a acknowledgeTransaction. Si no se llama a este método, la transaccion se reversará en 30 segundos.
$plus->acknowledgeTransaction();

De acuerdo a esa descripción. Como identifico que todo salió OK ?
Si imprimo la variable responseCode me retorna -100 en caso de Aceptar y -1 en caso de rechazar la transacción.

**Comment by gdespirito** [comment]
No había visto este issue. Entiendo que el tema de llamar o n a acknowledgeTransaction es medio extraño. 

Siempre debes llamar acknowledgeTransaction() (si te retorna 0 o -100 o lo que sea), excepto en el caso de que la transacción retorne 0 (éxito) y algo salga mal por tu lado (por ejemplo el monto de la transacción no coincide, o ya no te queda stock del producto porque alguien lo compró antes, etc). 

En ese caso, si transbank retorna "0" (indicando que la transacción ya está aprobada) pero tu NO mandas el acknowledgeTransaction, entonces esa transacción será reversada.
