### ISSUE TITLE
Usefulness of functions

### ISSUE THREAD

**Issue by LuisUrrutia** [freshworkstudio/transbank-web-services#23]
There are some functions I wonder if they're useful or if they're in the right place.

This function isn't used anywhere:
https://github.com/freshworkstudio/transbank-web-services/blob/33d9da4c6014b7d12e92d45b7877b471f9b0156f/src/TransbankService.php#L9

And this one:
https://github.com/freshworkstudio/transbank-web-services/blob/33d9da4c6014b7d12e92d45b7877b471f9b0156f/src/WebpayWebService.php#L79
Is for PatPass only, Shouldn't this be in PatPass class?

**Comment by gdespirito** [comment]
Is far a I can remember, the first one is used to change the logger interface used on the implementation. We package provides one Logging implementation, but you can change it using that method. 

The second one probably should need some refactor.
