### ISSUE TITLE
openssl_sign(): supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by dsrdnpblc** [freshworkstudio/transbank-web-services#27]
Buenos días, al suministrar la llave y certificado en producción se genera el siguiente error

openssl_sign(): supplied key param cannot be coerced into a private key

Pueden orientarme un poco hacia donde puede estar el problema?

**Comment by gdespirito** [comment]
Sin ver el código es difícil saber, pero creo que lo que estás cargando como llave privada no es válido. 
¿Seguro que estás colocando la llave privada correctamente?

**Comment by gdespirito** [comment]
Si quieres puedes contactarme a gonzalo@freshworkstudio.com y me mandas las llaves para probar y revisar si es un problema en el código. 

Saludos!
