### ISSUE TITLE
SoapFault sin faultstring

### ISSUE THREAD

**Issue by matiasah** [freshworkstudio/transbank-web-services#28]
Intentando pasar a producción estoy teniendo un error de SoapFault sin un mensaje de error.
![imagen](https://user-images.githubusercontent.com/5008893/48776792-87686d80-ecaf-11e8-90ed-6e8ca7b3e32a.png)
El faultcode que contiene es "soap:Server", los certificados los lee y luego sucede eso aquí.
![imagen](https://user-images.githubusercontent.com/5008893/48776877-cdbdcc80-ecaf-11e8-8273-a863027eff12.png)

**Comment by gdespirito** [comment]
Sería buenísimo si me puedes contactar a gonzalo@freshworkstudio.com. Si me
puedes compartir las llaves (no es recomendable compartirlas en todo caso)
te puedo ayudar a revisar de que se trata. Hay más issues relacionadas a
pasar a producción y me gustaría investigar mejor.

Saludos!

>
