### ISSUE TITLE
Se puede usar con webpay mall?

### ISSUE THREAD

**Issue by cristianmeza** [freshworkstudio/transbank-web-services#32]
Hola estimados, primero que todo quería darles gracias por haber creado este plugin, nos ha hecho mucho más fácil la tarea de las integraciones. Ahora mi duda es la siguiente: Este plugin se puede usar con webpay o transbank mall? Si no se puede, ustedes venden algo ya hecho? Gracias.

**Comment by gdespirito** [comment]
Deberías poder hacer la implementación MALL. No tenemos ningun servicio de pago, pero a usando este SDK no debería ser complejo. Saludos!
