### ISSUE TITLE
Lo sentimos. Su transacción no se pudo llevar a cabo. Error

### ISSUE THREAD

**Issue by DannyAndres** [freshworkstudio/transbank-web-services#33]
<img width="830" alt="captura de pantalla 2019-01-31 a la s 10 38 18" src="https://user-images.githubusercontent.com/19177489/52057804-cd11a400-2544-11e9-9d30-df48b87c9db0.png">
Al seguir los pasos de la página para implementar transbank con un certificado de prueba, llego a un error en el cual el dato de urlRedirection siempre equivale a esto lo que inevitablemente me manda a la imagen anterior con un mensaje super poco descriptivo diciendo
 ¨Lo sentimos. Su transacción no se pudo llevar a cabo.¨

`urlRedirection: "https://webpay3gint.transbank.cl/webpayserver/voucher.cgi",`

las primeras pruebas que realice funcionaron sin ningún problema, pero de un momento a otro comenzó este error a lo largo de todos los proyectos que iba realizando

Al comenzar el pago este es el código
```
 public function pagar()
    {
        $bag = CertificationBagFactory::integrationWebpayNormal();

        $webpay = TransbankServiceFactory::normal($bag);

        $webpay->addTransactionDetail(10, 'OrdenId'.rand(1,100000));

        $response = $webpay->initTransaction(url('/').'/pagarResponse', url('/').'/pagarFinish');

        return view('transbankRedirect.redirect',[
            'url' => $response->url,
            'token' => $response->token
        ]);
    }
```
termino redireccionando a response, lo que luego sin problemas llega  esta otra función
```
    public function pagarResponse(Request $request)
    {
        $bag = CertificationBagFactory::integrationWebpayNormal();

        $webpay = TransbankServiceFactory::normal($bag);
        $response = $webpay->getTransactionResult($request->token_ws);

        if ($response->detailOutput->responseCode == 0) { //y tambien aqui compruebo que la orden fue pagada
            $webpay->acknowledgeTransaction();
        }
        
        //return json_encode($response);
        return Redirect::to($response->urlRedirection);
    }
```
desde aquí no pasa, y tampoco obtengo un código de error que me ayude a entender que podría estar sucediendo

**Comment by gdespirito** [comment]
¿Qué hay en transbankRedirect.redirect.blade.php?
¿Por qué no usas el redirectorHelper que tiene la librería?

Acabo de probar webpay normal y me funciona como siempre lo ha hecho.

**Comment by DannyAndres** [comment]
transbankRedirect/redirect.blade.php
solo es un archivo que contiene la vista que ustedes proveen en su redirectorHelper dado que no puedo realizar un echo dentro de un controlador en laravel solo cree una vista con los datos respectivos para redireccionar y le pase tanto la url como el token los cuales llegan exitosamente via post a la siguiente vista
<img width="636" alt="captura de pantalla 2019-02-03 a la s 22 01 30" src="https://user-images.githubusercontent.com/19177489/52185550-505e1e80-27ff-11e9-8a18-3d528ae1152e.png">
el problema que tengo es al realizar el getTransactionResult en su video de ejemplo urlRedirection equivale a la ruta de salida la cual colocaron ustedes (https://webpay.dev/finish.php) mientras que mi ruta que se realiza con url('/').'/pagarFinish' que equivale a http://app.test/pagarFinish no es igual al dato de urlRedirection, el cual me entrega (https://webpay3gint.transbank.cl/webpayserver/voucher.cgi) lo que siempre me manda a una ventana con el mensaje de "lo sentimos"

**Comment by Makaaah** [comment]
Lo solucionaste?
me pasa lo mismo.

pero yo lo hice como enseñan en el ultimo video tutorial de transbank

`<?php
    require_once './vendor/autoload.php';

    use Transbank\Webpay\Webpay;
    use Transbank\Webpay\Configuration;

    $transaction = (new Webpay(Configuration::forTestingWebpayPlusNormal()))->getNormalTransaction();

    $tokenWs = filter_input(INPUT_POST, 'token_ws');
    $result = $transaction->getTransactionResult($tokenWs);
    $output = $result->detailOutput;
    if ($output->responseCode == 0) {
        echo '<script>windows.localStorage.clear();</script>';
        echo '<script>windows.localStorage.setItem("authorizationCode",'. $output->authorizationCode .' )</script>';
        echo '<script>windows.localStorage.setItem("amount",'. $output->amount.' );</script>';
        echo '<script>windows.localStorage.setItem("responseCode",'. $output->responseCode.' );</script>';
    }
?>
<?php if($output->responseCode == 0) : ?>
<form action="<?php echo $result->urlRedirection ?>" methos="post" id="return-form">
    <input type="hidden" name="token_ws" value="<?php echo $tokenWs ?>">
</form>
<script>
    document.getElementById('return-form').submit();
</script>
<?php endif; ?>`

**Comment by nickyapp** [comment]
Me encuentro con el mismo error, pero al ver en mi base de datos el responseCode es 0 y aun asi me arroja el error. 
Lograste solucionarlo ?

**Comment by zalongo** [comment]
Hola tengo el mismo problema 
![imagen](https://user-images.githubusercontent.com/27746820/81850824-802dc300-9526-11ea-8e51-9f5c907762e3.png)


`public function initTransaction(WebpayNormal $webpayNormal,Request $request)
	{

		$shippingFee = 0;

		$cartRepo = new CartRepository(new ShoppingCart());
		$items = $cartRepo->getCartItemsTransformed();
		$total = $cartRepo->getTotal(2,$shippingFee);
		$checkoutRepo = new CheckoutRepository;



		$order = $checkoutRepo->buildCheckoutItems([
			'reference' => Uuid::uuid4()->toString(),
			'courier_id' => 1,
			'customer_id' => $request->user()->id,
			'address_id' => $request->input('billing_address'),
			'order_status_id' => 6,
			'payment' => $request->input('payment'),
			'discounts' => 0,
			'total_products' => $cartRepo->getSubTotal(),
			'total' => $cartRepo->getTotal(),
			'total_paid' => 0,
			'tax' => $cartRepo->getTax()
		]);


		$webpayNormal->addTransactionDetail($cartRepo->getTotal(), 'order-' . $order->id);
		$response = $webpayNormal->initTransaction(route('checkout.webpay.response'), route('checkout.webpay.finish'));
			// Probablemente también quieras crear una orden o transacción en tu base de datos y guardar el token ahí.
		session(['token' => $response->token]);
		return \Freshwork\Transbank\RedirectorHelper::redirectHTML($response->url, $response->token);
	}

	public function response(WebpayPatPass $webpayPatPass,Request $request)
	{
		$result = $webpayPatPass->getTransactionResult();

		$order_id = str_replace('order-', '', $result->buyOrder);
		$order = \App\Shop\Orders\Order::find($order_id);

		session(['response' => $result]);

		if ($result->detailOutput->responseCode === 0) {
			$order->order_status_id = 1;
			$order->total_paid = $result->detailOutput->amount;
			$order->tracking_number = $result->buyOrder;
		}else{
			$order->order_status_id = 3;
		}

		$order->save();
		// dd($_POST['token_ws'], session('token'));

		  // Revisar si la transacción fue exitosa ($result->detailOutput->responseCode === 0) o fallida para guardar ese resultado en tu base de datos.

		return \Freshwork\Transbank\RedirectorHelper::redirectBackNormal($result->urlRedirection, $_POST['token_ws']);
	}

	public function finish()
	{
		// $cartRepo = new CartRepository(new ShoppingCart());
		// $cartRepo->clearCart();
		$result = session('response');
		session()->forget('response');
		dd($result);
		if ($result->detailOutput->responseCode === 0) {
			return view('front.checkout-success');
		}else{
			echo 'fallo';
		}
		  // Acá buscar la transacción en tu base de datos y ver si fue exitosa o fallida, para mostrar el mensaje de gracias o de error según corresponda
	}`
Lo loco es que cuando llega a "response", $result->detailOutput->responseCode si es 0 por lo que la orden se activa, pero despues muestra el mensaje de la imagen. y al momento de pinchar donde dice "intente nuevamente" me manda a "finish" y como $result->detailOutput->responseCode sigue siendo 0 me muestra return view('front.checkout-success');

**Comment by rodalcaino** [comment]
me parece que en el response te falta confirmar la transacción  $WebpayNormal->acknowledgeTransaction();

**Comment by zalongo** [comment]
Perfecto, eso era Gracias!!!

**Comment by juanpintorios** [comment]
Mismo problema persistente por acá.
No estoy desarrollando, sólo soy un comprador que lleva 2 dias intentando comprar.

Saludos!

**Comment by EugenioEscobar** [comment]
Hola, estoy teniendo el mismo problema al enviar la petición, solo que yo lo estoy haciendo en .net
```
protected void Page_Load(object sender, EventArgs e)
    {
        var transaction = new Webpay(Configuration.ForTestingWebpayPlusNormal()).NormalTransaction;
        var amount = 1000;
        var buyOrder = new Random().Next(100000, 999999999).ToString();
        var sessionId = "sessionId";

        var returnUrl = "http://localhost:55652/Default.aspx";
        var finalUrl = "http://localhost:55652/Default.aspx";

        var initResult = transaction.initTransaction(amount, buyOrder, sessionId, returnUrl, finalUrl);

        var formAction = initResult.url;
        var tokenWs = initResult.token;

        form1.Action = formAction;
        hdToken.Value = tokenWs;
        lblValor.Text = amount.ToString();
        lblBuyOrder.Text = buyOrder;

    }
```
y el .aspx está así:
```
         <form id="form1" runat="server" method="post">
            <div>
                <input id="hdToken" runat="server" name="token_ws" type="hidden" />
                <button type="submit" class="btn btn-primary">Pagar</button>
            </div>
        </form>
```
sé que no tiene sentido poner todos los valores por defecto en el page load, pero es porque solo estoy probando como sería una implementación para después agregarla a otro proyecto.

**Comment by crilaree** [comment]
Amigo, mismo error en integracion en .net, pudiste tener alguna solucion? ya que es un error bastante engorroso.

**Comment by gdespirito** [comment]
Este SDK esta obsoleto. Usa SOAP y transbank ahora ofrece un api REST. Usen el Sdk Oficial de Php

**Comment by brokercl** [comment]
estoy intentando en dart para flutter, me da el mismo error
