### ISSUE TITLE
Error: SoapFault Authorization failed, podria ayudarme?

### ISSUE THREAD

**Issue by paulioceano** [freshworkstudio/transbank-web-services#36]
Estoy tratando de usar su libreria, y me da el siguiente error:

![error](https://user-images.githubusercontent.com/15818783/53853672-c5f31100-3f9c-11e9-9197-9416f5e7f403.png)

El codigo es sencillo, siguiendo el mismo que tiene en el readme.

Me puede ayudar, por favor?

**Comment by gdespirito** [comment]
¿Pudiste solucionarlo?

**Comment by paulioceano** [comment]
No pude, aún tengo esa parte en stand by.
