### ISSUE TITLE
Error DOMDocument::loadXML()

### ISSUE THREAD

**Issue by jorgemorgado25** [freshworkstudio/transbank-web-services#38]
Algunas veces (no siempre) obtengo un error al regresar a la página de respuesta. 

Estoy usando el Framework Laravel y el error es: MethodNotAllowedHttpException. Esto pasa cuando se realiza una petición GET a una ruta POST. Obviamente la página de respuesta usa el método POST.

No tengo indicios de este error ocasional.... Así que obtuve la información del archivo /storage/logs/laravel.log

Espero sirva la información para actualizar la librería en caso de alguna falla de programación:

`[2019-03-08 13:30:19] production.ERROR: DOMDocument::loadXML(): Empty string supplied as input {"exception":"[object] (ErrorException(code: 0): DOMDocument::loadXML(): Empty string supplied as input at /home/medicin/medicinainterna.cl/tienda-sms/vendor/freshwork/transbank/src/TransbankSoap.php:116)`

**Comment by gdespirito** [comment]
¿En qué momento te da el MethodNotAllowedHttpException?

**Comment by jorgemorgado25** [comment]
El error ocurre en la página intermedia de respuesta donde se obtiene el token de Transbank para consultar el status. Esta ruta está por POST y obviamente está desprotegida del VerifyCsrfToken.

Gracias por responder.

**Comment by gdespirito** [comment]
Pero jamás te debería llegar un MethodNotAllowedHttpException, ya que siempre se llega a esa página por POST. Debe ser otra cosa, porque no le ha pasado a nadie más ese problema.

**Comment by DannyAndres** [comment]
Hola! Tengo exactamente el mismo problema, estuvo funcionando sin problemas todo estupendamente, pero un hoy en la mañana ningún post pasaba, dando timeout, al recurrir a los archivos log me arrojaba el siguiente error.
Empty string supplied as input at /var/www/app/vendor/freshwork/transbank/src/TransbankSoap.php:116)
Lo extraño es que al parecer surgió sin causa ya que el código no recibió ningún commit ni push, como también se acomodó la versión de desarrollo con las mismas credenciales de  producción para averiguar si es un error de código, a lo que funciona sin problemas. Es un error que solo sucede en la máquina donde está alojado el código, que podría ser? 
**actualización**: de pronto sin causa nuevamente, el error desapareció y soy incapaz de reproducirlo

**Comment by suflito** [comment]
Hola! Tengo el mismo problema pero no he podido solucionarlo. De un momento a otro empezó a aparecer:

DOMDocument::loadXML(): Empty string supplied as input
TransbankSoap.php:116

Volvi a las pruebas más básicas:

        $bag = CertificationBagFactory::integrationWebpayNormal();
        $plus = TransbankServiceFactory::normal($bag);
        $plus->addTransactionDetail((int) 1000, 'orden1'); //Amount and BuyOrder
        $response = $plus->initTransaction(route('payments.test1'), route('payments.test2'));


Pero me sigue saliendo el mismo error. Alguien tiene una pista de que podría ser?

EDIT: igual que el post de arriba se solucionó solo sin que hiciera nada

**Comment by gdespirito** [comment]
Hola! Estos les sigue pasando?
