### ISSUE TITLE
Código de autorización en la anulación (cancelar) de una compra.

### ISSUE THREAD

**Issue by ErSoul** [freshworkstudio/transbank-web-services#39]
Hola, en la documentación de esta librería dice que en el método WebpayCaptureNullify::nullify() hay que mandar un código de autorización, este código es en caso de que ya se haya efectuado el pago de la compra. Pero, en el primer formulario de webPay hay una opción de *anular*, el cual en realidad es *Cancelar* (abortar) el pago. ¿De dónde saco este código de autorización, si según la API de Transbank dice que dicho código es devuelto por el método getTransactionResult()?

PD: tuve que cambiar el acceso de WebpayCaptureNullifyWebService::classmap de private a protected ya que laravel me lo pedía así.

**Comment by gdespirito** [comment]
Hola!. ¿Finalmente pudiste solucionar este problema? ¿Me podrías indicar como replicar el error?

**Comment by gdespirito** [comment]
Acabo de subir el fix para pasar de private a protected. Gracias por la info.
