### ISSUE TITLE
function mcrypt_get_iv_size() is deprecated [PHP 7.1]

### ISSUE THREAD

**Issue by irenkai** [freshworkstudio/transbank-web-services#4]
La dependencia **xmlseclibs.php** ocupa funciones deprecadas en PHP 7.1 especificamente en la funcion generateSessionKey, se resuelve marcandolas con **"@"** (al menos temporalmente, habria que revisar la dependencia para ver si ha actualizado para funcionar en 7.1)

```
public function generateSessionKey() 
        {       
        $key = '';
        if (!empty($this->cryptParams['cipher']) && !empty($this->cryptParams['mode'])) {
            $keysize = @mcrypt_module_get_algo_key_size($this->cryptParams['cipher']);
            /* Generating random key using iv generation routines */
            if (($keysize > 0) && ($td = @mcrypt_module_open(MCRYPT_RIJNDAEL_256, '', $this->cryptParams['mode'], ''))) {
                if ($this->cryptParams['cipher'] == MCRYPT_RIJNDAEL_128) {
                    $keysize = 16;
                    if ($this->type == XMLSecurityKey::AES256_CBC) {
                        $keysize = 32;
                    } elseif ($this->type == XMLSecurityKey::AES192_CBC) {
                        $keysize = 24;
                    }
                }
                while (strlen($key) < $keysize) {
                    $key .= @mcrypt_create_iv(@mcrypt_enc_get_iv_size($td), MCRYPT_RAND);
                }
                @mcrypt_module_close($td);
                $key = substr($key, 0, $keysize);
                $this->key = $key;
            }
        }
        return $key;
    }


```

**Comment by gdespirito** [comment]
Creo que tengo que encontrar una mejor solución para esto. 
Aún no estoy muy seguro como, pero intentaré actualizar este archivo que es de los pocos que no edité directamente, ya que vienen de ejemplo en la documentación de transbank. 

Saludos!

**Comment by clsource** [comment]
una opción es usar `error_reporting(0)` o `error_reporting(E_ERROR)`. para no mostrar esos mensajes, sin tener que modificar el core del código. :)

**Comment by jcabezas** [comment]
Al parecer mcrypt se sacará del core PHP en las versiones 7.2.x y 8, hay que encontrar una librería alternativa, la cual podría ser openssl pero aun no podido lograr implementar.

Saludos

**Comment by gdespirito** [comment]
Me suena a que la mejor opción es OpenSSL, pero no le he dado el tiempo para tratar de cambiar la implementación. Si alguien pueden enviar un PR, sería increíble.

**Comment by kattatzu** [comment]
@gonzunigad envío un PR agregando el @ a los métodos de Mcrypt para solucionar el problemas mientras se busca una alternativa.

https://github.com/freshworkstudio/transbank-web-services/pull/7

Saludos

**Comment by gdespirito** [comment]
@kattatzu ya apliqué el merge, gracias. Esperemos que alguien pueda resolver el problema de raíz.

Saludos!

**Comment by gdespirito** [comment]
Esto ya está resuelto. Gracias al PR de @Morti08
