### ISSUE TITLE
Classmap must be protected

### ISSUE THREAD

**Issue by techguydev** [freshworkstudio/transbank-web-services#45]
Tengo este error:

`PHP Fatal error:  Access level to Freshwork\Transbank\WebpayCaptureNullify\WebpayCaptureNullifyWebService::$classmap must be protected (as in class Freshwork\Transbank\TransbankWebService) or weaker in /Users/lmatab/Sites/compraengrupo/vendor/freshwork/transbank/src/WebpayCaptureNullify/WebpayCaptureNullifyWebService.php on line 20

In WebpayCaptureNullifyWebService.php line 20:
                                                                                                                                        
  Access level to Freshwork\Transbank\WebpayCaptureNullify\WebpayCaptureNullifyWebService::$classmap must be protected (as in class Fr  
  eshwork\Transbank\TransbankWebService) or weaker   `

**Comment by techguydev** [comment]
Solucionado:

En WebpayCaptureNullifyWebService.php debemos cambiar  $classmap de la clase a protected:

Asi:

   protected static $classmap = array(
        'nullify' => Nullify::class,
        'nullificationInput' => NullificationInput::class,
        'baseBean' => BaseBean::class,
        'nullifyResponse' => NullifyResponse::class,
        'nullificationOutput' => NullificationOutput::class,
        'capture' => Capture::class,
        'captureInput' => CaptureInput::class,
        'captureResponse' => CaptureResponse::class,
        'captureOutput' => CaptureOutput::class
    );

**Comment by gdespirito** [comment]
Gracias. Acabo de subir el fix con el tag 1.1.6

**Comment by techguydev** [comment]
Gracias @gonzunigad , para todos aquellos que quieran tener exactamente la version que Gonzalo actualizó  pueden hacerlo con el siguiente  comando:

composer require freshwork/transbank:dev-master#59b47d0662f380b071d413519dda0511ca8792f4

**Comment by gdespirito** [comment]
No creo que sea necesario. Solo debes hacer composer update y se debería descargar la versión 1.1.6, que contiene el fix.

**Comment by techguydev** [comment]
No se porque pero con el composer update no me trajo la version
actualizada, por eso comparti el comando directo al commit.
