### ISSUE TITLE
Laravel - error $client_private_key

### ISSUE THREAD

**Issue by angelmaturanat** [freshworkstudio/transbank-web-services#46]
Estimado, muy agradecido del maravilloso trabajo que realizaste/realizaron.

Actualmente me encuentro desarrollando un sistema el cual requiere pago vía webpay y al momento de querer enviar como parametro "WebpayNormal $webpayNormal" en el método de mi controlador se cae y me muestra el siguiente error:

<img width="1097" alt="imagen" src="https://user-images.githubusercontent.com/23390169/63288110-efbd9d00-c289-11e9-9697-867ba3215d8b.png">

Estuve revisando el código de lo que implementaste y al parecer no está recibiendo los parámetros "client_private_key" y "client_certificate" en el constructor de **CertificationBag**.

Agradecería mucho tu ayuda, detallo las versiones que estoy utilizando:
- Laravel 5.8.*
- PHP 7.3.8
- freshwork/transbank 1.1^

Saludos!

**Comment by DevelopersQuierosushi** [comment]
Hola buenas, me pasa exactamente lo mismo...

Saludos... excelente trabajo realizado...

**Comment by gdespirito** [comment]
Intenta acgtualizar la librería con `composer update`. Ojalá a la versión 1.2.0 ;)
Esa tiene mejor integración con Laravel. En la documentación hay info al respecto. De todas formas, el mismo código que usas ahora también debe funcionar al actualizar. 
La mejor integración con Laravel te evita tener que crear el certification bag en cada método del controller y lo hace de manera centralizada para toda la app. 

Había un error en la versión 1.1.6, por eso es imporatnte actualizar. 

Info sobre la integración con Laravel: https://github.com/freshworkstudio/transbank-web-services#laravel

**Comment by angelmaturanat** [comment]
Buenísimo! funcionó, solo dejar en el composer.json "freshwork/transbank": "^1.2" tal como indicas y aplicar el composer update.

Saludos y muchas gracias!
