### ISSUE TITLE
Problemas con la libreria en php >= 7.0

### ISSUE THREAD

**Issue by fbuccioni** [freshworkstudio/transbank-web-services#47]
Hola, me estoy cambiando a php 7 pero no he podido de ninguna maner hacer posible que pueda andar la librería, funciona super en php 5.6 pero en 7, 7,1 o 7.2 sigue sin funcionar el mismo codigo sin tocar.

He hablado con el soporte de transbank, validando los certificados y generando unos nuevos sin ningún problema, pero sigue mostrándome el mismo error en todas las versiones.

    Verificar que la información del certificado sea correcta

No entiendo por que esta sucediendo.

**Comment by gdespirito** [comment]
La librería funciona incluso en PHP 7.4. No debería fallarte. ¿Que error te arroja? ¿Me muestras cómo lo estás usando?

**Comment by gdespirito** [comment]
Si pruebas con los nuevos ejemplos que vienen con el paquete ¿te funciona?
https://github.com/freshworkstudio/transbank-web-services#ejemplos
