### ISSUE TITLE
Redirección Patpass

### ISSUE THREAD

**Issue by albertosoho** [freshworkstudio/transbank-web-services#48]
Hola!

Realizando un pago patpass al llegar al response no vuelve a re-dirigirme al voucher de transbank, $patpass->getTransactionResult() returna '0' (hay token_ws  y $response viene correcto). La página simplemente queda en blanco. 

Me falta algo? Gracias por todo!

response.php
```<?php 

use Freshwork\Transbank\CertificationBagFactory;  
use Freshwork\Transbank\TransbankServiceFactory;  
use Freshwork\Transbank\RedirectorHelper;  
  
include 'vendor/autoload.php';

// Obtenemos los certificados y llaves para utilizar el ambiente de integración de Webpay Normal.  
$bag = CertificationBagFactory::integrationPatPass();  
  
$patpass = TransbankServiceFactory::patpass($bag);  

$response = $patpass->getTransactionResult();  

return RedirectorHelper::redirectBackNormal($response->urlRedirection); 

?>
```

Debug $response

```object(Freshwork\Transbank\WebpayStandard\TransactionResultOutput)#4696 (8) { ["accountingDate"]=> string(4) "0427" ["buyOrder"]=> string(2) "66" ["cardDetail"]=> object(Freshwork\Transbank\WebpayStandard\CardDetail)#4702 (2) { ["cardNumber"]=> string(4) "6623" ["cardExpirationDate"]=> NULL } ["detailOutput"]=> object(Freshwork\Transbank\WebpayStandard\TransactionDetailOutput)#4698 (7) { ["authorizationCode"]=> string(4) "1213" ["paymentTypeCode"]=> string(2) "VN" ["responseCode"]=> int(0) ["sharesNumber"]=> int(0) ["amount"]=> string(5) "15980" ["commerceCode"]=> string(12) "597044444432" ["buyOrder"]=> string(2) "66" } ["sessionId"]=> NULL ["transactionDate"]=> string(29) "2020-04-27T03:18:12.437-03:00" ["urlRedirection"]=> string(57) "https://webpay3gint.transbank.cl/webpayserver/voucher.cgi" ["VCI"]=> string(3) "TSY" } ```

Debug $_POST['token'];

```array(1) { ["token_ws"]=> string(64) "e56f94be6f0ebc95f9964f5280c9fc2a3db9e5ecc3d8b597c9420600407a6222" }```

**Comment by gdespirito** [comment]
Hola. Efectivamente te falta hacer la redirección a Transbank. 
En este video puedes ver el flujo completo: https://www.youtube.com/watch?v=VavxN-a9SIk

**Comment by gdespirito** [comment]
Perdón, lo leí mal. Quizás no es el método `redirectBackNormal` y tengas que usar `redirectHTML`.

**Comment by albertosoho** [comment]
Gracias @gonzunigad !

El problema está en que según la docu es:

```return RedirectorHelper::redirectBackNormal($response->urlRedirection);```

Pero realmente debe ser 

```echo RedirectorHelper::redirectBackNormal($response->urlRedirection);```

**Comment by gdespirito** [comment]
👌
