### ISSUE TITLE
The signature or decryption was invalid

### ISSUE THREAD

**Issue by JosmerD** [freshworkstudio/transbank-web-services#49]
Estoy tratando de hacer pruebas con el portal de webpay usando el codigo de comercio de integracion 597020000540 y me muestra este error The signature or decryption was invalid, si uso un codigo de comercio de produccion me funciona sin problemas. 

Anexo mi codigo estoy trabajando en c#
certificate.Add("environment", "INTEGRACION");
certificate.Add("public_cert", certFolder + "\\certificates\\597020000540\\tbk.pem");
certificate.Add("webpay_cert", certFolder + "\\certificates\\597020000540\\597020000540.p12");
certificate.Add("password", "");
certificate.Add("commerce_code", "597020000540");

**Comment by gdespirito** [comment]
Hola. ¿Esto tiene algo que ver con este SDK en PHP? 
veo que usas .NET y existe un SDK oficial para ese lenguaje en https://github.com/TransbankDevelopers/transbank-sdk-dotnet

Esos SDK incluyen los crtificados y no debes configurarlos manualmente: `var transaction =
    new Webpay(Configuration.ForTestingWebpayPlusNormal()).NormalTransaction;`
