### ISSUE TITLE
integración múltiples empresas 

### ISSUE THREAD

**Issue by zalongo** [freshworkstudio/transbank-web-services#50]
Hola muy buena la solución que nos brindan, nos ahorran un montón de trabajo. Les cuento que quiero implementar un sistema de pago para un conjunto de emprendedores que tengo asociados en un sitio web. La idea es que las ventas salgan por el sitio pero que la plata llegue al emprendedor que corresponda la compra. Eso es webpay mall? Se puede integrar con este sdk?

**Comment by gdespirito** [comment]
Hola, eso efectivamente es Webpay Plus Mall.  Si se puede integrar con el
SDK.


GONZALO DE-SPIRITO

*FRESHWORK* STUDIO CHILE

+569 8815 3776 |  <gonzalo@freshwork.cl>gonzalo@freshwork.cl

**Comment by denisonl84** [comment]
Hola, Gonzalo, buen día. Agradecido de ante mano por tu colaboración con este paquete. Quería comentarte que instalé tu paquete en laravel, version 7.x y todo bien. Sin embargo, una vez aprobados los tests de integración y por ende, hice pase a prodcción, se me presenta el problema siguiente: Una vez que ya el banco (en este caso banco estado) ya "aprueba" la transacción, (lo hace porque me llega notificación a mi correo del cobro) me arroja error 500. En este sentido, reviso el log de laravel y obtengo esto:


 Error ["[object] (ErrorException(code: 0): openssl_sign(): supplied key param cannot be coerced into a private key at /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/wss/xmlseclibs.php:693)\n[stacktrace]\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'openssl_sign():...', '/home/tecalefl/...', 693, Array)\n#1 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/wss/xmlseclibs.php(693): openssl_sign('<ds:SignedInfo ...', NULL, false, 1)\n#2 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/wss/xmlseclibs.php(781): XMLSecurityKey->signOpenSSL('<ds:SignedInfo ...')\n#3 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/wss/xmlseclibs.php(1570): XMLSecurityKey->signData('<ds:SignedInfo ...')\n#4 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/wss/xmlseclibs.php(1590): XMLSecurityDSig->signData(Object(XMLSecurityKey), '<ds:SignedInfo ...')\n#5 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/wss/soap-wsse.php(287): XMLSecurityDSig->sign(Object(XMLSecurityKey))\n#6 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/TransbankSoap.php(97): WSSESoap->signSoapDoc(Object(XMLSecurityKey), Array)\n#7 [internal function]: Freshwork\\Transbank\\TransbankSoap->__doRequest('<?xml version=\"...', 'https://webpay3...', '', 1, 0)\n#8 [internal function]: SoapClient->__call('getTransactionR...', Array)\n#9 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/TransbankWebService.php(128): call_user_func_array(Array, Array)\n#10 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/WebpayStandard/WebpayStandardWebService.php(75): Freshwork\\Transbank\\TransbankWebService->callSoapMethod('getTransactionR...', Object(Freshwork\\Transbank\\WebpayStandard\\TransactionResult))\n#11 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/freshwork/transbank/src/WebpayWebService.php(179): Freshwork\\Transbank\\WebpayStandard\\WebpayStandardWebService->getTransactionResult('e7486f66a8f2747...')\n#12 /home/tecalefl/public_html/isispa.cl/isispacore/app/Http/Controllers/ECommerceController.php(322): Freshwork\\Transbank\\WebpayWebService->getTransactionResult()\n#13 [internal function]: App\\Http\\Controllers\\ECommerceController->response(Object(Freshwork\\Transbank\\WebpayNormal))\n#14 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)\n#15 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('response', Array)\n#16 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ECommerceController), 'response')\n#17 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()\n#18 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()\n#19 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#20 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#21 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#22 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#23 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#24 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#25 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#26 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#27 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))\n#28 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#29 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#30 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#31 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#32 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#33 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#34 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#35 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#36 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))\n#37 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#38 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#39 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))\n#40 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#41 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#42 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#43 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#44 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#45 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#46 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#47 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#48 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#49 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#50 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#51 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#52 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#53 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#54 /home/tecalefl/public_html/isispa.cl/isispacore/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))\n#55 /home/tecalefl/public_html/isispa.cl/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#56 {main}\n"] .


¿Alguna razón que sepas? te agradezco de alguna ayuda que puedas darme.

Saludos cordiales,

**Comment by zalongo** [comment]
Hola. en estos tiempos de cuarentena intenté hacer la integración con Laravel pero no hubo caso, ahora estoy tratando de hacer la integración solo con php dentro de laravel pero llegue a un error que no entiendo. Todavía no logro salir a webpay. 
![cod](https://user-images.githubusercontent.com/27746820/99262524-dee93780-27fc-11eb-8892-9420192b9ffb.jpg)
![error](https://user-images.githubusercontent.com/27746820/99262537-e27cbe80-27fc-11eb-8005-270e6ed00fb1.jpg)

**Comment by zalongo** [comment]
Hola. en estos tiempos de cuarentena intenté hacer la integración con Laravel pero no hubo caso, ahora estoy tratando de hacer la integración solo con php dentro de laravel pero llegue a un error que no entiendo. Todavía no logro salir a webpay.
![cod](https://user-images.githubusercontent.com/27746820/99263264-ba418f80-27fd-11eb-81d7-a1c49a48084d.jpg)
![error](https://user-images.githubusercontent.com/27746820/99263267-bb72bc80-27fd-11eb-8f6b-038cbc15b1f2.jpg)

**Comment by gdespirito** [comment]
¡Hola!
Ahora que salió el API REST de Transbank, te recomiendo aprovechar de hacer
el cambio y utilizar esta nueva API para hacer tu integración.
Si necesitas ayuda directa, entra al slack de transbank:
https://join-transbankdevelopers-slack.herokuapp.com/

¡Saludos!


GONZALO DE-SPIRITO

*FRESHWORK* STUDIO CHILE

+569 8815 3776 |  <gonzalo@freshwork.cl>gonzalo@freshwork.cl
