### ISSUE TITLE
Transaction Token doesn't register in Transbank

### ISSUE THREAD

**Issue by raiarainne** [freshworkstudio/transbank-web-services#54]
I sent transbank requirement document to Transbank support to get production key.
To fill their requirement table contents, i have tested several times to record Payment Token
After test, they are saying they couldn't find the token on their side
What's wrong with this?

**Comment by raiarainne** [comment]
Hi gonzunigad
I am sorry 
But it's very wired problem 
I used your library 
And it works properly in test mode 
But Transbank says they can't find my payment token on their side 
In this case, what cause the issue?

**Comment by gonzunigad** [comment]
I think it may be because you should be implementing using the REST API. This SDK uses the OLD SOAP API. 
This is the documentation of the officila SDK that has support to the REST API: https://transbankdevelopers.cl/documentacion/webpay-plus

**Comment by raiarainne** [comment]
I used SOAP API
followed your instr
