### ISSUE TITLE
Variables de session se pierden al finalizar proceso de tranabank

### ISSUE THREAD

**Issue by jonhy95** [freshworkstudio/transbank-web-services#55]
Estimados, estoy teniendo el siguiente inconveniente, luego de ser procesada y aprobada la transaccion con transbank y ser redirigido a la urlfinal, las variables de session se pierden , hay alguna forma de corregir este error ? 

`<?php 
session_start();
require_once '../vendor/autoload.php';include '../logica/conexion.php';
$con = new Conexion; 

use Transbank\Webpay\Webpay;
use Transbank\Webpay\Configuration;

$transaction = (new Webpay(Configuration::forTestingWebpayPlusNormal()))->getNormalTransaction();

$tokenWs = filter_input(INPUT_POST,'token_ws');
$result = $transaction->getTransactionResult($tokenWs);
$output = $result->detailOutput;
$comercio = 'WebPay';
$total = $output->amount;
//$query_cantidad = $con->conexion->prepare("SELECT cantidad FROM escala_creditos WHERE total = ?");
//$query_cantidad->bind_param('i',$total);
$query_cantidad = $con->obtenerdatos("cantidad","escala_creditos","total = ?",array($total));
$cantidad = $query_cantidad[0]['cantidad'];
$fechaautorizacion = DateTime::createFromFormat('Y-m-d\TH:i:s.uT',$result->transactionDate);
$fechaautorizacion->setTimezone(new DateTimeZone('America/Santiago'));
$fecha = $fechaautorizacion->format('Y-m-d H:i:s');
$ordencompra = $output->buyOrder;
$codigoautorizacion = $output->authorizationCode;
$numerotarjeta = str_pad($result->cardDetail->cardNumber, 16, "X", STR_PAD_LEFT);
$idusuario = $_SESSION['idusuario'];
$sid = $_SESSION['sid'];
if($output->sharesNumber == 0){
	$numerocuotas = 0;
	$montocuotas = 0;
}else{
	$numerocuotas = $output->sharesNumber;
	$montocuotas = $output->sharesAmount;
}
if($output->paymentTypeCode == 'VD'){
	$tipoventa = 'Débito';	
}elseif($output->paymentTypeCode == 'VN'){
	$tipoventa = 'Normal';	
}elseif($output->paymentTypeCode == 'VC'){
	$tipoventa = 'En Cuotas';	
}elseif($output->paymentTypeCode == 'SI' or $output->paymentTypeCode == 'S2' or $output->paymentTypeCode == 'NC'){
	$tipoventa = 'Cuotas S/I';	
}elseif($output->paymentTypeCode == 'VP'){
	$tipoventa = 'Prepago';	
}else{
	$tipoventa = '';	
}
if ($output->responseCode == 0) {
	
	echo '	<script>
				window.localStorage.clear();
        		window.localStorage.setItem("result",JSON.stringify('.json_encode($result).'));
			</script>';
	
//	
//	$query = $con->insertar("creditos","'$ordencompra','$codigoautorizacion','$numerotarjeta','$numerocuotas','$montocuotas','$tipoventa','$total','$cantidad','$fecha','Aprobada','123','$comercio','$idusuario'");
	
	$query = $con->insertar("?,?,?,?,?,?,?,?,?,?,?,?,?,?,?","creditos",array($ordencompra,$codigoautorizacion,$numerotarjeta,$numerocuotas,$montocuotas,$tipoventa,$total,$cantidad,$fecha,"Aprobada","123",$comercio,$idusuario,$sid,$tokenWs));
//	$query_creditos = $con->actualizar("usuarios","creditos = creditos + '$cantidad'","idusuario = '$idusuario'");
	$query_creditos = $con->actualizar("creditos = creditos + ?","usuarios","idusuario = ?",array($cantidad,$idusuario));
}

?>
<?php if($output->responseCode == 0){?>
<form action="<?php echo $result->urlRedirection?>" method="post" id="return-form">
	<input type="hidden" name="token_ws" value="<?php echo $tokenWs;?>">
</form>

<script>
	document.getElementById('return-form').submit();
</script>
<?php }?>
`

**Comment by gdespirito** [comment]
Hola!

Primero que todo, recuerda que este paquete usa tecnología SOAP y esta ya no está disponible. Ahora solo puedes hacer integraciones con la nueva API REST de Transbank. Hay un SDK oficial de PHP ahí. 
https://transbankdevelopers.cl/documentacion/como_empezar#

SEgundo: Esto pasa por una actualización de Chrome 80. Debes habilitar tus cookies con el flag Secure; y SameSite=None
