### ISSUE TITLE
Undefined class constant 'Freshwork\Transbank\Log\LoggerInterface::INFO'

### ISSUE THREAD

**Issue by kattatzu** [freshworkstudio/transbank-web-services#6]
La constante se llama LEVEL_INFO, se hace referencia a INFO en la clase Freshwork\Transbank\Log\LogHandler  en la función log: 

public static function log($string, $level = LoggerInterface::INFO, $type = null)

**Comment by zorrigas** [comment]
No sé si tiene que ver, pero estoy intentando hacer funcionar los logs  y no lo consigo! 🔢

**Comment by gdespirito** [comment]
Solucionado.
